let post = {
  user: userID, //number
  timeposted: Date.now(), //date
  prompt: promptText, //text
  likes: 0, //count
  replies: [
    {
      reply: message, //text
      replyBy: userID, //number or login name
      date: Date.now(), //date
      likes: 0, //counter
    },
  ],
};

const user = {
  username: "user1",
  password: "123",
  loggedin: true,
  postCount: 20,
  activePrompt: Userprompt,
};

const oneDay = 1000 * 60 * 60 * 24;
const oneWeek = 1000 * 60 * 60 * 24 * 7;

const currentTime = Date.now();

// Outline of a potential prompt Schema 
let Userprompt = {
  user: userID, //number
  timeposted: Date.now(), //date
  post, // is this reffering to associated posts? If so wouldn't it be easier to include in the post data 
  expiresIn: oneDay,
};

let usedPrompts = [];

// let communalPrompts = []

let handWrittenPrompts = [
  "Pirate Captain Desperately trying to impress his crew",
  "Robot increasingly anxious about a mysterious bolt that fell off of their body",
  "Door to door ice salesman in the Sahara desert",
  "The chosen one of legend, convinced all others are fakes",
  "Villain giving their evil speech moments before being thwarted",
  "Lost dad who is sure he can find his way home without directions",
  "A sad but slightly threatening Clown",
  "Dragon that lost their horde in a stock market crash",
  "Person who got bit in a zombie apocalypse but didn't tell anyone for some reason",
  "Vampire trying really hard to blend in",
  "Detective trying to figure out [Something obvious]",
  "Guy who is way too into devil sticks",
  "Person incorrectly quoting [Insert figure]",
  "Person explaining how they definitely aren't having midlife crisis",
  "Beekeeper who hasn't realised their hive is definitley not bees",
  "Reddit Moderator",
  "Crypto Bro trying to rug pull",
  "Evil advisor to the sickly king",
  "Mysterious wanderer trying to out-mystery everyone",
  "Person who doesn't realise they're clearly haunted",
  "Courtroom witness who is fuzzy on ALL details",
  "Widow who definitely killed her husband",
  "Inventor who keeps accidenttally recreating commonly available devices",
  "Best man delivering an increasingly concerning wedding speech",
  "Person at the watercooler trying to outdo everyone with how cool their weekend was",
  "Lottery winner trying to keep it on the downlow",
  "Person who's having an intense trip",
  "Spam bots",
  "Debater 'playing devils advocate' but clearly on the side of the devil",
  "Cult recruiters trying to out-recruit all others",
  "Self-Proclaimed Empath",
  "Celebrity issuing a vague apology clearly written by a PR team",
  "Person with poor reading comprehension"
];

let descriptors = [
  "Unlucky",
  "Fearsome",
  "Anxious",
  "Foolish",
  "Wise",
  "Brash",
  "Overconfident",
  "Suspicious",
  "Dastardly",
  "Noble",
  "Edgy",
  "Pretentious",
  "Insecure",
  "Mischevious",
  "Cowardly",
  "Smug",
  "Untrustworthy",
  "Loud",
  "Tiny",
  "Huge",
  "Sneaky",
  "Sleepy",
  "Frenzied",
  "Furious",
  "Thoughtful",
  "Unprofessional",
  "Incompetant",
  "Smooth-Talking",
  "Downtrodden",
  "Shy",
  "Posessed",
  "Oblivious",
  "Zombified",
  "Rowdy",
  "Devious",
  "Unhinged",
  "Normal",
  "Regular",
  "Evil",
  "Shadow",
  "Reverse",
  "Friendly",
  "Flamboyant",
  "Old-Timey",
  "Petulant",
  "Dyslexic",
  "Helpful",
  "Clumsy",
  "Glamorous",
  "Conspiratorial",
  "Fickle",
  "Depressed",
  "Dubious",
  "Verbose",
  "Incoherant",
  "Rhyming",
  "Self-Serious",
  "Morose",
  "Post-Apocalyptic",
  "Cantankerous",
  "Forgetful",
  "Gout-Addled",
  "Sinister",
  "Riddlesome",
  "Enigmatic",
  "Sullen",
  "Reserved",
  "Time-Travelling",
  "Tragic",
  "Lucky",
  "Snooty",
  "Uncompromising",
  "Unsettling",
  "Polite",
  "Agreeable",
  "Classy",
  "Rambunctious",
  "Scatterbrained",
  "Grounded",
  "Skeptical",
  "Cynical",
  "Prideful",
  "Easily-Persuaded",
  "Self-Contradicting",
  "Barely-Conscious",
  "Rapidly Approaching",
  "Green",
  "Magical",
  "Pedantic",
  "Fraudulent",
  "So-Called",
  "Alleged",
  "Self-Proclaimed",
  "Unethical",
  "Principled",
  "Humble",
  "Cheerful",
  "Optimistic",
  "Burnt-Out",
  "Dramatic",
  "Hysterical",
  "Thin-Skinned",
  "Worried",
  "Vain",
  "Boastful",
  "Conniving",
  "Patronising",
  "Aloof",
  "Apathetic",
  "Timid",
  "Immature",
  "Knowledgable",
  "Insincere",
  "Morbid",
  "Jealous",
  "Petty",
  "Peaceful",
  "Aspiring",
  "Inexperienced",
  "Cultured",
  "Dignified",
  "Capable",
  "Debonair",
  "Elegant",
  "Passionate",
  "Popular",
  "Unpopular",
  "Famous",
  "Infamous",
  "Relaxed",
  "Chill",
  "Respectful",
  "Sentimental",
  "Buisnesslike",
  "Competitive",
  "Experimental",
  "Escaped",
  "Preachy",
  "Subversive",
  "Retired",
  "Dishonourably Discharged",
  "Solemn",
  "Sarcastic",
  "Performative",
  "Criminal",
  "Gullible",
  "Indecisive",
  "Naive",
  "Contrarian",
  "Opinionated",
  "Well-Meaning",
  "Disgraced",
  "Small-Time",
  "Big-Shot",
  "Renowned",
  "Honourable"
];

let nouns = [
  "Wizard",
  "Witch",
  "Knight",
  "Cowboy",
  "Alien",
  "Robot",
  "Explorer",
  "Deep Sea Diver",
  "Karate Master",
  "Monster Hunter",
  "Spacefarer",
  "Villain",
  "Hero",
  "Antihero",
  "Artist",
  "Burglar",
  "Pirate",
  "Clown",
  "Mime",
  "Miner",
  "Cave-Diver",
  "Ghost Hunter",
  "Astronaut",
  "Gamer",
  "Tourist",
  "Gladiator",
  "Chef",
  "Vampire",
  "Cheerleader",
  "Caveman",
  "Zombie",
  "Wrestler",
  "Street Magician",
  "Doctor",
  "Ninja",
  "Forest Elf",
  "Fisherman",
  "Scientist",
  "Werewolf",
  "Monster",
  "Cryptid",
  "Lumberjack",
  "Detective",
  "Mobster",
  "Academic",
  "CEO",
  "Engineer",
  "Genie",
  "Hippie",
  "Mermaid",
  "Stunt Actor",
  "Knight",
  "Investor",
  "Middle Manger",
  "DJ",
  "Merchant",
  "Soothsayer",
  "Emperor",
  "Nerd",
  "Skydiver",
  "Pensioner",
  "Influencer",
  "Biker",
  "Wife Guy",
  "Bigfoot",
  "Jazz Musician",
  "Mountaineer",
  "Prospector",
  "Jester",
  "King",
  "Queen",
  "Prince",
  "Princess",
  "Noble",
  "Delivery Driver",
  "Racer",
  "Bandit",
  "Diva",
  "Weeaboo",
  "Ghoul",
  "Ghost",
  "Buisnessman",
  "Farmer",
  "Cyborg",
  "Photographer",
  "Papperazi",
  "Journalist",
  "Liar",
  "Spy",
  "Acrobat",
  "Bounty Hunter",
  "Martial Artist",
  "Castaway",
  "Survivalist",
  "Bard",
  "Aristocrat",
  "Newspaper Kid",
  "Chimney Sweep",
  "Orphan",
  "Bodybuilder",
  "Barbarian",
  "Bogeyman",
  "Conspiracy Theorist",
  "Inventor",
  "Surfer",
  "Dentist",
  "Hitman",
  "Bodyguard",
  "Psychologist",
  "Monk",
  "Shopkeeper",
  "Guard",
  "Poet",
  "Head Teacher",
  "Escapologist",
  "Archeologist",
  "Astronomer",
  "Paleontologist",
  "Superhero",
  "Supervillain",
  "Rockstar",
  "Rival",
  "Scholar",
  "Poliician",
  "Cultist"
];

// let verbs = ["fighting", ""];

// const promptSelectArray = [
//   promptSelectOne() { let promptOne = randomDescriptor.concat(" ", randomNoun) },
//   promptSelectTwo()  {},
//   promptSelectThree() {}
// ];

// and then make it always run the code to check the usedPrompts and add new successful prompts to it

let randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
let randomDescriptor = descriptors[Math.floor(Math.random() * descriptors.length)];

let promptOne = randomDescriptor + " " + randomNoun;
let promptTwo = randomNoun + " " + randomNoun + " " + fusion;
// test to see if this just will print two of the same nouns

//array.rpototype.find() - array.find looking through usedPrompts, if match is found, returns True - we want it to return 'undefined'

// Would a string literal be the way to print 'userName userPrompt userMessage' for posts

let todaysPrompt = "";
// maybe title this userPrompt? Sometimes all users get the same prompt, sometimes users get different individualised ones

//Maybe delete uploads folder? doesn't seem necessary if images are just for pfps but maybe I am wrong

// Displays users as either - [Username] The [Prompt] OR [Username] subheading: [Prompt]